package com.example.myapplication1.studio

import androidx.compose.animation.core.EaseIn
import androidx.compose.animation.core.EaseOut
import androidx.compose.animation.core.FastOutSlowInEasing
import androidx.compose.animation.core.LinearEasing
import androidx.compose.ui.graphics.BlendMode
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.DpSize
import androidx.compose.ui.unit.dp
import dev.piotrprus.particleemitter.CanvasEmitterConfig.Shape
import dev.piotrprus.particleemitter.EdgeBehavior

/** Color from an `#RRGGBB` or `#AARRGGBB` string (pure Kotlin — no Android framework). */
private fun hex(value: String): Color {
    val s = value.removePrefix("#")
    val n = s.toLong(16)
    val argb = if (s.length <= 6) 0xFF000000L or n else n
    return Color(argb.toInt())
}

private fun sz(w: Int, h: Int): DpSize = DpSize(w.dp, h.dp)

/**
 * The curated gallery. Fifteen scenes that, together, exercise the *entire*
 * particle-emitter API surface:
 *
 * - **Start regions**: POINT (fountain), OVAL (nebula/portal/bubbles/fireflies), RECT (fire),
 *   H_LINE (snow/confetti/rain/emoji/blossom/aurora), V_LINE (meteor/wind).
 * - **Particle shapes**: Circle, PathShape (star/heart), Image (glow / tall veil / streak,
 *   tinted), Text (emoji).
 * - **Edge behaviours**: None, Bounce, Wrap as scene defaults; Stick via the live control.
 * - **Gravity**: off (portal/fireflies), down, up (nebula/fire/bubbles/aurora), sideways (wind, −90).
 * - **Blend**: SrcOver (confetti/emoji/blossom), Screen (most), Plus (portal), Lighten (wind).
 * - **Scale**: grow (start < target) and shrink-to-nothing (target 0..0, fire/meteor).
 * - **Spread**: narrow/directional, wide, full 360.
 * - **hideInStartRegion**, rotation on non-circle shapes, full **easing** variety, and
 *   ambient **[SceneMotion]** so localized emitters stay alive when untouched.
 */
object SceneCatalog {
    val scenes: List<SceneSpec> = listOf(
        SceneSpec(
            id = "auroraFountain",
            title = "Aurora Fountain",
            subtitle = "Luminous jets arc and fall",
            description = "A glowing fountain erupts from a single point at the base, flinging cyan, teal and violet droplets up in a tight plume that arcs over under gravity and bounces softly off the floor.",
            features = listOf(
                "POINT start region — a single-source jet",
                "Strong upward force + narrow spread → columnar plume",
                "Gravity DOWN bends each stream into a parabola",
                "Screen blend for additive glow on a dark stage",
                "Bounce edge behaviour — droplets rebound off the floor",
            ),
            particlePerSecond = 160,
            anchor = Anchor.BOTTOM_CENTER,
            regionShape = Shape.POINT,
            shapeKinds = listOf(ShapeKind.CIRCLE),
            lifespan = 1500..2000, fadeOut = 900..1500, scaleTime = 500..900,  // tapering comet jets; lifespan≈fadeOut so no invisible tail is simulated
            colors = listOf(hex("#CC36F0E0"), hex("#E04DD8FF"), hex("#B300E5C8"), hex("#CC7C5CFF"), hex("#99A0F0FF"), hex("#E0CFFBFF")),
            sizes = listOf(sz(7, 7), sz(10, 10), sz(4, 4), sz(6, 6)),
            spread = -16..16, blend = BlendMode.Screen,
            initialForce = 360..480,
            startScale = 0..1, targetScale = 1..2,
            gravityStrength = 240f,
            edge = EdgeBehavior.Bounce(damping = 0.45f),
            alphaEasing = EaseIn, scaleEasing = EaseOut,
            gradient = listOf(hex("#FF050912"), hex("#FF0A1424"), hex("#FF050A10")),
            accent = hex("#FF4DD8FF"),
            atmosphere = Atmosphere.Aurora,
            motion = SceneMotion.Sway(amplitudeDp = 74f, periodMs = 7000),
        ),
        SceneSpec(
            id = "nebulaDrift",
            title = "Nebula Drift",
            subtitle = "A slow cosmic cloud, breathing",
            description = "Soft bokeh embers bloom outward from a clean oval core and drift weightlessly through deep purples and cosmic blue. Additive blending fuses overlapping glows into a living interstellar cloud.",
            features = listOf(
                "OVAL start region — particles born on the perimeter",
                "Image particles: a soft, per-colour-tinted bokeh sprite",
                "hideInStartRegion keeps the bright core clean",
                "Full 360° spread for an even radial drift",
                "Near-zero gravity for a weightless float",
            ),
            particlePerSecond = 38,
            anchor = Anchor.CENTER,
            regionShape = Shape.OVAL,
            regionWidthDp = 240f, regionHeightDp = 200f,
            shapeKinds = listOf(ShapeKind.GLOW_IMAGE, ShapeKind.GLOW_IMAGE, ShapeKind.CIRCLE),
            lifespan = 9000..16000, fadeOut = 9000..16000, scaleTime = 6000..11000,
            colors = listOf(hex("#33B36AF0"), hex("#40C04AD8"), hex("#3A8A4FFF"), hex("#4D6E5BE0"), hex("#2E9D5BC8"), hex("#26D08AF5")),
            sizes = listOf(sz(40, 40), sz(64, 64), sz(96, 96), sz(128, 128)),
            spread = -180..180, blend = BlendMode.Screen,
            initialForce = 12..38, rotation = 0..360,
            startScale = 0..0, targetScale = 2..3,
            gravityStrength = 1f, gravityAngle = 180,
            edge = EdgeBehavior.None, hideInStartRegion = true,
            alphaEasing = EaseOut, scaleEasing = FastOutSlowInEasing,
            gradient = listOf(hex("#FF0A0612"), hex("#FF150A24"), hex("#FF08060F")),
            accent = hex("#FFB36AF0"),
            atmosphere = Atmosphere.Nebula,
            motion = SceneMotion.Drift(radiusDp = 72f, periodMs = 17000),
        ),
        SceneSpec(
            id = "winterSnow",
            title = "Winter Snowfall",
            subtitle = "Drifting flakes on a midnight sky",
            description = "Soft white and pale-blue flakes spill from the entire top edge and drift down on gentle gravity, wrapping at the screen edges so the snow never stops falling.",
            features = listOf(
                "H_LINE band spanning the full screen width",
                "Gentle downward gravity for a slow, settling fall",
                "Wrap edge behaviour → an endless, seamless snowfield",
                "Calm low birth-rate + long lifespan for unhurried pacing",
                "Slight side spread for natural drift",
            ),
            particlePerSecond = 42,
            anchor = Anchor.TOP_FULL_WIDTH,
            regionShape = Shape.H_LINE, fullWidthRegion = true,
            shapeKinds = listOf(ShapeKind.CIRCLE),
            lifespan = 9000..14000, fadeOut = 9000..14000, scaleTime = 900..1600,
            colors = listOf(hex("#FFFFFFFF"), hex("#F2EAF4FF"), hex("#E0DCEEF8"), hex("#C7D6F0EE"), hex("#A9C4E8DC"), hex("#8FB3DEC8")),
            sizes = listOf(sz(3, 3), sz(5, 5), sz(7, 7), sz(10, 10)),
            spread = 160..200, blend = BlendMode.Screen,
            initialForce = 30..70,
            startScale = 0..0, targetScale = 1..1,
            gravityStrength = 28f,
            edge = EdgeBehavior.Wrap,
            alphaEasing = LinearEasing, scaleEasing = EaseOut,
            gradient = listOf(hex("#FF0A0E1A"), hex("#FF121A2E"), hex("#FF1C2740")),
            accent = hex("#FFC7D6F0"),
        ),
        SceneSpec(
            id = "emberFlame",
            title = "Ember Flame",
            subtitle = "A living campfire of rising embers",
            description = "Warm embers spill from a small fire base, drawn upward by buoyancy as they shrink to glowing specks and dissolve into the dark. Additive blending fuses the cores into a flickering flame.",
            features = listOf(
                "RECT start region — embers across a fire bed",
                "Gravity UP (angle 180) simulates heat buoyancy",
                "Shrink-to-nothing scale (target 0..0) for dying embers",
                "Warm additive glow via Screen blend",
                "Narrow upward spread forms a tapering flame column",
            ),
            particlePerSecond = 150,
            anchor = Anchor.BOTTOM_CENTER,
            regionShape = Shape.RECT,
            regionWidthDp = 90f, regionHeightDp = 18f,
            shapeKinds = listOf(ShapeKind.CIRCLE),
            lifespan = 1400..2600, fadeOut = 1300..2500, scaleTime = 1400..2600,
            colors = listOf(hex("#FFFFF1C4"), hex("#FFFFD27A"), hex("#F2FFA63D"), hex("#E6FF6A1A"), hex("#CCFF3B0A"), hex("#B3E02810")),
            sizes = listOf(sz(8, 8), sz(6, 6), sz(4, 4), sz(3, 3)),
            spread = -22..22, blend = BlendMode.Screen,
            initialForce = 60..150,
            startScale = 1..2, targetScale = 0..0,
            gravityStrength = 90f, gravityAngle = 180,
            edge = EdgeBehavior.None,
            alphaEasing = EaseOut, scaleEasing = EaseOut,
            gradient = listOf(hex("#FF120703"), hex("#FF1F0C04"), hex("#FF050201")),
            accent = hex("#FFFFA63D"),
            atmosphere = Atmosphere.Heat,
            motion = SceneMotion.Sway(amplitudeDp = 24f, periodMs = 3800),
        ),
        SceneSpec(
            id = "festivalConfetti",
            title = "Festival Confetti",
            subtitle = "Paper stars and hearts rain down",
            description = "A celebratory cascade of opaque paper confetti — stars and hearts in vivid party colours — tumbling from the top, spinning end over end, and lightly bouncing as they settle.",
            features = listOf(
                "PathShape star + heart that genuinely rotate",
                "Opaque SrcOver so shapes read as solid paper, not glow",
                "Random multi-shape mix (stars + hearts)",
                "H_LINE band across the full top edge",
                "Bounce edge behaviour for a soft floor settle",
            ),
            particlePerSecond = 70,
            anchor = Anchor.TOP_FULL_WIDTH,
            regionShape = Shape.H_LINE, fullWidthRegion = true,
            shapeKinds = listOf(ShapeKind.STAR_PATH, ShapeKind.HEART_PATH),
            lifespan = 4200..6500, fadeOut = 4000..6500, scaleTime = 300..600,
            colors = listOf(hex("#FFFF3B6B"), hex("#FFFFC542"), hex("#FF3BD6C6"), hex("#FF7C5CFF"), hex("#FF4FC3F7"), hex("#FFFF8A3D")),
            sizes = listOf(sz(14, 14), sz(18, 18), sz(12, 12), sz(22, 22)),
            spread = -35..35, blend = BlendMode.SrcOver,
            initialForce = 60..150, rotation = 0..360,
            startScale = 1..1, targetScale = 1..1,
            gravityStrength = 160f,
            edge = EdgeBehavior.Bounce(damping = 0.35f),
            alphaEasing = EaseIn, scaleEasing = FastOutSlowInEasing,
            gradient = listOf(hex("#FF1A1033"), hex("#FF120A24"), hex("#FF080513")),
            accent = hex("#FFFFC542"),
            backdrop = false,
        ),
        SceneSpec(
            id = "neonRain",
            title = "Neon Rain",
            subtitle = "Cyberpunk downpour on wet chrome",
            description = "Thin neon streaks fall from the full width of the sky, accelerating under heavy gravity before splashing off the floor in low cyan-green sparks — a rain-soaked alley in additive glow.",
            features = listOf(
                "Image streaks (a vertical glow sprite) read as falling rain",
                "Strong downward gravity for an accelerating fall",
                "H_LINE band across the whole sky",
                "Bounce edge behaviour — drops splash off the floor",
                "Screen blend for luminous neon on a dark backdrop",
            ),
            particlePerSecond = 170,
            anchor = Anchor.TOP_FULL_WIDTH,
            regionShape = Shape.H_LINE, fullWidthRegion = true,
            shapeKinds = listOf(ShapeKind.STREAK_IMAGE, ShapeKind.CIRCLE),
            lifespan = 1100..1600, fadeOut = 700..1100, scaleTime = 300..600,  // streaky rain tails; lifespan≈fadeOut (no invisible tail)
            colors = listOf(hex("#CC6CFFE6"), hex("#B33CF0D2"), hex("#E64DFFC8"), hex("#A632B5FF"), hex("#9970F0FF"), hex("#CC9CFFEA")),
            sizes = listOf(sz(3, 3), sz(4, 4), sz(2, 2)),
            spread = -6..6, blend = BlendMode.Screen,
            initialForce = 160..240,
            startScale = 1..1, targetScale = 1..1,
            gravityStrength = 340f,
            edge = EdgeBehavior.Bounce(damping = 0.22f),
            alphaEasing = EaseIn, scaleEasing = LinearEasing,
            gradient = listOf(hex("#FF060A12"), hex("#FF0A1420"), hex("#FF03070D")),
            accent = hex("#FF4DFFC8"),
        ),
        SceneSpec(
            id = "arcanePortal",
            title = "Arcane Portal",
            subtitle = "A breathing ring of emerald and gold",
            description = "A glowing magic ring spins in the dark, leaking sparks of emerald, teal and gold as star-sparkles slowly drift outward and dissolve into the void.",
            features = listOf(
                "Ring emitter — an OVAL spawn perimeter at centre",
                "hideInStartRegion conceals the ring's interior",
                "Star PathShape sparkles with continuous rotation",
                "Additive Plus blend for an intense luminous bloom",
                "360° radial spread with zero gravity",
            ),
            particlePerSecond = 90,
            anchor = Anchor.CENTER,
            regionShape = Shape.OVAL,
            regionWidthDp = 200f, regionHeightDp = 200f,
            shapeKinds = listOf(ShapeKind.STAR_PATH, ShapeKind.GLOW_IMAGE, ShapeKind.CIRCLE),
            lifespan = 2600..4200, fadeOut = 2400..4000, scaleTime = 1400..2600,
            colors = listOf(hex("#FF36F1B0"), hex("#FF18C9A4"), hex("#FFFFD877"), hex("#CC0FA37F"), hex("#B3F5E6A8"), hex("#996FFFD4")),
            sizes = listOf(sz(10, 10), sz(16, 16), sz(8, 8), sz(22, 22)),
            spread = -180..180, blend = BlendMode.Plus,
            initialForce = 35..90, rotation = -220..220,
            startScale = 0..0, targetScale = 1..2,
            gravityStrength = 0f,
            edge = EdgeBehavior.None, hideInStartRegion = true,
            alphaEasing = EaseOut, scaleEasing = FastOutSlowInEasing,
            gradient = listOf(hex("#FF03110D"), hex("#FF071F18"), hex("#FF02070A")),
            accent = hex("#FF36F1B0"),
            atmosphere = Atmosphere.Nebula,
            motion = SceneMotion.Orbit(radiusDp = 40f, periodMs = 11000),
        ),
        SceneSpec(
            id = "starfall",
            title = "Starfall",
            subtitle = "Quiet glyphs drifting down the night",
            description = "Soft monochrome sparkles spill from the top edge and drift down through a deep midnight sky, tumbling slowly as they fade — the Text-particle path, kept painterly.",
            features = listOf(
                "Text particles rasterised via a TextMeasurer (monochrome glyphs)",
                "Per-particle rotation on Text shapes",
                "H_LINE band across the full screen width",
                "Gentle downward gravity → a slow, drifting fall",
                "SrcOver blend keeps each glyph crisp",
            ),
            particlePerSecond = 24,
            anchor = Anchor.TOP_FULL_WIDTH,
            regionShape = Shape.H_LINE, fullWidthRegion = true,
            shapeKinds = listOf(ShapeKind.TEXT_EMOJI),
            lifespan = 4200..6200, fadeOut = 4200..6200, scaleTime = 320..560,
            colors = listOf(hex("#FFEAF2FF")),
            sizes = listOf(sz(20, 20), sz(14, 14), sz(26, 26), sz(11, 11)),
            spread = -22..22, blend = BlendMode.SrcOver,
            initialForce = 30..90, rotation = -180..180,
            startScale = 0..0, targetScale = 1..1,
            gravityStrength = 150f,
            edge = EdgeBehavior.None,
            alphaEasing = EaseIn, scaleEasing = FastOutSlowInEasing,
            gradient = listOf(hex("#FF0B0F2A"), hex("#FF14193D"), hex("#FF050713")),
            emojis = listOf("✦", "✧", "✶", "✷", "⋆"),
            accent = hex("#FFB9C7FF"),
            backdrop = false,
        ),
        SceneSpec(
            id = "risingBubbles",
            title = "Rising Bubbles",
            subtitle = "The quiet breath of the deep",
            description = "Translucent pale-cyan bubbles drift up from the seabed, swelling and wobbling as they rise through dark water, then wrapping back to the depths.",
            features = listOf(
                "Gravity UP (angle 180) lifts the bubbles",
                "Wrap edge behaviour recirculates them endlessly",
                "Translucent low-alpha circles + Screen blend → glow halos",
                "OVAL band across the seabed",
                "Wide spread for a gentle horizontal wobble",
            ),
            particlePerSecond = 34,
            anchor = Anchor.BOTTOM_FULL_WIDTH,
            regionShape = Shape.OVAL, fullWidthRegion = true, regionHeightDp = 40f,
            shapeKinds = listOf(ShapeKind.CIRCLE),
            lifespan = 7000..11000, fadeOut = 7000..11000, scaleTime = 2200..3600,
            colors = listOf(hex("#3DAEEAFF"), hex("#4CD7E6FF"), hex("#33BFE8D8"), hex("#66E6F4FF"), hex("#2A8FD4C0"), hex("#80F0FAFF")),
            sizes = listOf(sz(10, 10), sz(16, 16), sz(24, 24), sz(32, 32)),
            spread = -26..26, blend = BlendMode.Screen,
            initialForce = 40..90,
            startScale = 0..0, targetScale = 1..1,
            gravityStrength = 42f, gravityAngle = 180,
            edge = EdgeBehavior.Wrap,
            alphaEasing = EaseIn, scaleEasing = EaseOut,
            gradient = listOf(hex("#FF02141F"), hex("#FF04293D"), hex("#FF062F44")),
            accent = hex("#FF4CD7E6"),
        ),
        SceneSpec(
            id = "meteorShower",
            title = "Meteor Shower",
            subtitle = "Cobalt streaks rake the night sky",
            description = "A radiant shower of blue-white meteors streaks diagonally from the top-left corner, leaving glowing trails that flare before vanishing into the dark.",
            features = listOf(
                "V_LINE corner emitter at the screen edge",
                "Tight directional spread aimed down-right (~122–138°)",
                "High force → fast streaking motion",
                "Image streak heads rotated to align with travel",
                "Short fadeOut < lifespan for a trailing-tail decay",
            ),
            particlePerSecond = 90,
            anchor = Anchor.TOP_LEFT,
            regionShape = Shape.V_LINE, regionHeightDp = 120f,
            shapeKinds = listOf(ShapeKind.STREAK_IMAGE, ShapeKind.CIRCLE),
            lifespan = 900..1500, fadeOut = 650..1100, scaleTime = 700..1300,
            colors = listOf(hex("#FFEAF4FF"), hex("#E6A9D4FF"), hex("#CC5FA8FF"), hex("#FF9FC6E6"), hex("#FFFFE7B0"), hex("#B33A6FA0")),
            sizes = listOf(sz(7, 7), sz(4, 4), sz(5, 5)),
            spread = 122..138, blend = BlendMode.Screen,
            initialForce = 340..460, rotation = 120..140,
            startScale = 1..2, targetScale = 0..0,
            gravityStrength = 90f,
            edge = EdgeBehavior.None,
            alphaEasing = FastOutSlowInEasing, scaleEasing = EaseIn,
            gradient = listOf(hex("#FF0A0712"), hex("#FF140A1E"), hex("#FF050309")),
            accent = hex("#FF9FC6E6"),
        ),
        SceneSpec(
            id = "stardustWind",
            title = "Stardust Wind",
            subtitle = "Embers carried on a sideways gale",
            description = "Golden motes pour from the left edge and are swept across the screen by a sideways gravitational wind, twinkling as they tumble out of frame to the right.",
            features = listOf(
                "Sideways gravity (angle −90 = right) — a horizontal wind",
                "Lighten blend mode for a soft additive shimmer",
                "V_LINE emitter spanning the full left edge",
                "Star + glow + spark mix with rotation",
                "Toggle gravity off to watch the wind die instantly",
            ),
            particlePerSecond = 80,
            anchor = Anchor.LEFT_CENTER,
            regionShape = Shape.V_LINE, fullHeightRegion = true,
            shapeKinds = listOf(ShapeKind.GLOW_IMAGE, ShapeKind.CIRCLE, ShapeKind.STAR_PATH),
            lifespan = 3200..4200, fadeOut = 1900..3200, scaleTime = 1500..3000,  // motes streak then twinkle out; lifespan≈fadeOut (no invisible tail)
            colors = listOf(hex("#FFFFE9B0"), hex("#FFFFD27A"), hex("#E6FFC15A"), hex("#B3FFB347"), hex("#99FFE08A")),
            sizes = listOf(sz(6, 6), sz(9, 9), sz(4, 4), sz(12, 12)),
            spread = 60..120, blend = BlendMode.Lighten,
            initialForce = 40..90, rotation = -180..180,
            startScale = 0..1, targetScale = 1..2,
            gravityStrength = 120f, gravityAngle = -90,
            edge = EdgeBehavior.None,
            alphaEasing = EaseOut, scaleEasing = FastOutSlowInEasing,
            gradient = listOf(hex("#FF120A03"), hex("#FF1E1408"), hex("#FF070402")),
            accent = hex("#FFFFD27A"),
            motion = SceneMotion.Bob(amplitudeDp = 84f, periodMs = 9000),
        ),
        // ---- New large-scale scenes (this enhancement pass) ----
        SceneSpec(
            id = "fireflies",
            title = "Fireflies",
            subtitle = "A drifting swarm on a summer night",
            description = "A calm, screen-wide swarm of glowing motes born around a huge oval, wandering weightlessly with no gravity and twinkling in and out as each short life fades. Soft yellow-green glow with the odd star sparkle.",
            features = listOf(
                "Large OVAL spawn so motes scatter across the stage",
                "Gravity OFF — weightless wandering via 360° spread",
                "Twinkle: short matched lifespan/fadeOut so the swarm shimmers",
                "Warm translucent glow + Screen blend",
                "Circles mixed with occasional rotating star sparkles",
            ),
            particlePerSecond = 60,
            anchor = Anchor.CENTER,
            regionShape = Shape.OVAL, fullWidthRegion = true, fullHeightRegion = true,
            shapeKinds = listOf(ShapeKind.CIRCLE, ShapeKind.CIRCLE, ShapeKind.STAR_PATH),
            lifespan = 2600..4400, fadeOut = 2600..4400, scaleTime = 1200..2200,
            colors = listOf(hex("#CCEBFF7A"), hex("#B0FFE36B"), hex("#E0FFF59A"), hex("#FFFFC04D"), hex("#A8FFD98C"), hex("#FFFFFFB0")),
            sizes = listOf(sz(5, 5), sz(8, 8), sz(11, 11), sz(4, 4)),
            spread = 0..360, blend = BlendMode.Screen,
            initialForce = 6..22, rotation = 0..360,
            startScale = 0..1, targetScale = 1..2,
            gravityStrength = 0f,
            edge = EdgeBehavior.None,
            alphaEasing = EaseIn, scaleEasing = EaseOut,
            gradient = listOf(hex("#FF050A18"), hex("#FF0A1428"), hex("#FF13203A")),
            accent = hex("#FFE8FF6A"),
        ),
        SceneSpec(
            id = "cherryBlossom",
            title = "Cherry Blossom",
            subtitle = "Petals drifting on a spring breeze",
            description = "Soft pink and white petals spill from the top edge and tumble down on a gentle breeze, rotating end over end as they're carried off-vertical, then wrapping back to the sky.",
            features = listOf(
                "H_LINE band across the full screen width",
                "Heart + teardrop-petal PathShape silhouettes that tumble",
                "Off-vertical spread → a leaning spring breeze",
                "Opaque SrcOver so petals read as soft paper",
                "Wrap edge behaviour → an endless petal-fall",
            ),
            particlePerSecond = 40,
            anchor = Anchor.TOP_FULL_WIDTH,
            regionShape = Shape.H_LINE, fullWidthRegion = true,
            shapeKinds = listOf(ShapeKind.HEART_PATH, ShapeKind.PETAL_PATH),
            lifespan = 7000..11000, fadeOut = 7000..11000, scaleTime = 900..1800,
            colors = listOf(hex("#FFFFE6F0"), hex("#FFFFC2DA"), hex("#F2FF9EC4"), hex("#E6F49BB8"), hex("#FFFFFFFF"), hex("#CCFFD6E6")),
            sizes = listOf(sz(14, 14), sz(18, 18), sz(11, 11), sz(22, 22)),
            spread = 135..225, blend = BlendMode.SrcOver,
            initialForce = 30..80, rotation = -360..360,
            startScale = 0..0, targetScale = 1..1,
            gravityStrength = 22f,
            edge = EdgeBehavior.Wrap,
            alphaEasing = EaseOut, scaleEasing = FastOutSlowInEasing,
            gradient = listOf(hex("#FF1A0E16"), hex("#FF2A1422"), hex("#FF120810")),
            accent = hex("#FFFFB3D1"),
            backdrop = false,
        ),
        SceneSpec(
            id = "auroraVeil",
            title = "Aurora Veil",
            subtitle = "A northern-lights curtain, rising",
            description = "Tall soft columns of green, teal and violet light bloom along a wide band across the sky and drift slowly upward, shimmering as they swell and fade — a luminous aurora curtain breathing over a polar night.",
            features = listOf(
                "Full-width H_LINE band across the sky",
                "Tall VEIL Image sprites fuse into a curtain via Screen blend",
                "Gravity UP (angle 180) for a slow upward drift",
                "Near-vertical narrow spread → shimmering light columns",
                "Long lifespan + full-life fade for an ethereal dissolve",
            ),
            particlePerSecond = 46,
            anchor = Anchor.CENTER,
            regionShape = Shape.H_LINE, fullWidthRegion = true,
            shapeKinds = listOf(ShapeKind.VEIL_IMAGE, ShapeKind.VEIL_IMAGE, ShapeKind.CIRCLE),
            lifespan = 8000..14000, fadeOut = 8000..14000, scaleTime = 5000..9000,
            colors = listOf(hex("#4D5BF0A8"), hex("#5933E0C4"), hex("#402FD0E0"), hex("#338A7CFF"), hex("#4DB060F0"), hex("#33CFAFF5")),
            sizes = listOf(sz(8, 8), sz(5, 5), sz(12, 12)),
            spread = -7..7, blend = BlendMode.Screen,
            initialForce = 14..40,
            startScale = 0..0, targetScale = 1..2,
            gravityStrength = 6f, gravityAngle = 180,
            edge = EdgeBehavior.None,
            alphaEasing = EaseOut, scaleEasing = FastOutSlowInEasing,
            gradient = listOf(hex("#FF02060F"), hex("#FF06121F"), hex("#FF010308")),
            accent = hex("#FF36F0C4"),
            atmosphere = Atmosphere.Aurora,
        ),
        SceneSpec(
            id = "willOWisp",
            title = "Will-o'-the-Wisp",
            subtitle = "A few lanterns drifting through fog",
            description = "Not a swarm but a handful of soft lanterns — large, slow glows that wander upward through the dark, each one bright enough to follow with your eye.",
            features = listOf(
                "Sparse, hero-scale particles — a low birth rate, not a field",
                "Large soft glow sprites with a long, slow life",
                "Near-weightless upward drift, wandering on ambient motion",
                "Screen blend so overlapping lanterns pool into warm light",
                "Tap-to-place sets a lantern down anywhere",
            ),
            particlePerSecond = 5,
            anchor = Anchor.BOTTOM_FULL_WIDTH,
            regionShape = Shape.OVAL, fullWidthRegion = true, regionHeightDp = 80f,
            shapeKinds = listOf(ShapeKind.GLOW_IMAGE),
            lifespan = 7000..12000, fadeOut = 7000..12000, scaleTime = 4000..8000,
            colors = listOf(hex("#CCFFE08A"), hex("#B3FFC15A"), hex("#A66FE0D0"), hex("#99FFD27A")),
            sizes = listOf(sz(40, 40), sz(64, 64), sz(96, 96)),
            spread = -40..40, blend = BlendMode.Screen,
            initialForce = 10..30,
            startScale = 0..1, targetScale = 2..3,
            gravityStrength = 4f, gravityAngle = 180,
            edge = EdgeBehavior.None,
            alphaEasing = EaseOut, scaleEasing = FastOutSlowInEasing,
            gradient = listOf(hex("#FF06080F"), hex("#FF0C1018"), hex("#FF04060A")),
            accent = hex("#FFFFD27A"),
            motion = SceneMotion.Drift(radiusDp = 60f, periodMs = 16000),
        ),
    )
}
